### ISSUE TITLE
what‘s this "[E2][80][93]"?

### ISSUE THREAD

**Issue by r00tSe7en** [x90skysn3k/brutespray#36] opened 2020-03-03 04:48 UTC
[+] ACCOUNT FOUND: [telnet] Host: 127.0.0.1 User: [E2][80][93] Password: admin00 [SUCCESS]
kali4.0

**Comment by x90skysn3k** [comment] 2020-03-16 20:12
bug with medusa, E2 80 93 is the hex characters in UTF-8 encoding for dash "-".  
Duplicate of #33

**Closed by x90skysn3k** 2020-03-16 20:12 UTC
